server:
  port: 8080
#  servlet:
#    context-path: /haejwoing

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haejwoing
    username: root
    password: root
mybatis:
  type-aliases-package: com.haejwoing.back.model.dto
  mapper-locations: classpath:mappers/*.xml
